version: '2'
services:

  elasticsearch:
    build: elasticsearch/
    image: elasticsearch:latest
    labels:
      io.rancher.sidekicks: elasticsearch-config
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    volumes_from:
      - elasticsearch-config
    stdin_open: true

  elasticsearch-config:
    build: elasticsearch-config/
    image: elasticsearch-config:latest
    volumes:
      - /etc/elasticsearch
    stdin_open: true

  logstash:
    build: logstash/
    image: logstash:latest
    labels:
      io.rancher.sidekicks: logstash-config
    ports:
      - 5000:5000/tcp
    command:
      - -f
      - /etc/logstash/conf.d/
    links:
      - elasticsearch
      - influxdb
    volumes_from:
      - logstash-config
    stdin_open: true

  logstash-config:
    build: logstash-config/
    image: logstash-config:latest
    volumes:
      - /etc/logstash/conf.d
    stdin_open: true

  kibana:
    build: kibana/
    image: kibana:latest
    labels:
      io.rancher.sidekicks: kibana-config
    ports:
      - 5601:5601/tcp
    links:
      - elasticsearch
      - influxdb
      - prometheus
    volumes_from:
      - kibana-config
    stdin_open: true

  kibana-config:
    build: kibana-config/
    image: kibana-config:latest
    volumes:
      - /opt/kibana/config/
    stdin_open: true
