version: '2'
services:
#  prometheus-rancher-exporter:
  #build: prometheus-rancher-exporter/
#    labels:
#      io.rancher.container.pull_image: always
#    tty: true
#    image: alpine:latest
#    stdin_open: true
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    environment:
      GF_SERVER_ROOT_URL: http://grafana.lab:3000
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,digiapulssi-breadcrumb-panel,jdbranham-diagram-panel,savantly-heatmap-panel,mtanda-heatmap-epoch-panel,mtanda-histogram-panel
    labels:
      io.rancher.sidekicks: grafana-config
    links:
      - influxdb
      - elasticsearch
      - prometheus
    volumes_from:
      - grafana-config
    stdin_open: true

  grafana-config:
    build: grafana-config/
    image: grafana-config:latest
    command:
      - cat
    volumes:
      - /var/lib/grafana/
    stdin_open: true

  influxdb:
    image: tutum/influxdb:latest
#    ports:
#      - 2003:2003/tcp
#      - 8083:8083/tcp
#      - 8086:8086/tcp
#      - 8090:8090/tcp
    environment:
      GRAPHITE_BINDING: :2003
      GRAPHITE_DB: rancher
      PRE_CREATE_DB: grafana;prometheus;rancher
    stdin_open: true

  kibana:
    build: kibana/
    image: kibana:latest
    labels:
      io.rancher.sidekicks: kibana-config
    ports:
      - 5601:5601/tcp
    links:
      - elasticsearch
      - influxdb
      - prometheus
    volumes_from:
      - kibana-config
    stdin_open: true

  kibana-config:
    build: kibana-config/
    image: kibana-config:latest
    volumes:
      - /opt/kibana/config/
    stdin_open: true

#  alertmanager:
  #build: alertmanager/
#    tty: true
#    image: alpine:latest
#    links:
#    - prometheus:prometheus
#    stdin_open: true

  logstash:
    build: logstash/
    image: logstash:latest
    labels:
      io.rancher.sidekicks: logstash-config
    ports:
      - 5000:5000/tcp
    command:
      - -f
      - /etc/logstash/conf.d/
    links:
      - elasticsearch
      - influxdb
    volumes_from:
      - logstash-config
    stdin_open: true

  logstash-config:
    build: logstash-config/
    image: logstash-config:latest
    volumes:
      - /etc/logstash/conf.d
    stdin_open: true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090/tcp
    labels:
      io.rancher.sidekicks: prometheus-config
    command:
      - -alertmanager.url=http://alertmanager:9093
      - -config.file=/etc/prometheus-config/prometheus.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
    links:
      - node-exporter
      - cadvisor
      - logstash
      - rancher-exporter
    volumes_from:
      - prometheus-config
    stdin_open: true

  prometheus-config:
    build: prometheus-config/
    image: prometheus-config:latest
    volumes:
      - /etc/prometheus-config/
    stdin_open: true

  logspout:
    build: logspout/
    image: logspout:latest
    tty: true
    stdin_open: true
    domainname: lab
    environment:
      EXCLUDE_LABEL: logspout.exclude
      ROUTE_URIS: 'logstash://logstash:5000'
    links:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'

#  pushgateway:
  #build: pushgateway/
#    tty: true
#    image: alpine:latest
#    links:
#    - prometheus:prometheus
#    stdin_open: true

  cadvisor:
    image: google/cadvisor:latest
    privileged: true
    ports:
      - 9104:9104/tcp
    network_mode: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
    stdin_open: true
    command:
      - --port=9104
      - --listen_ip=0.0.0.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  elasticsearch:
    build: elasticsearch/
    image: elasticsearch:latest
    labels:
      io.rancher.sidekicks: elasticsearch-config
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    volumes_from:
      - elasticsearch-config
    stdin_open: true

  elasticsearch-config:
    build: elasticsearch-config/
    image: elasticsearch-config:latest
    volumes:
      - /etc/elasticsearch
    stdin_open: true
  node-exporter:
    labels:
      io.rancher.scheduler.global: 'true'
    image: prom/node-exporter:latest
    stdin_open: true
  rancher-exporter:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
    stdin_open: true
    tty: true
    image: infinityworks/prometheus-rancher-exporter:latest
    links:
      - influxdb
#  node-exporter:
#    build: node-exporter/
#    labels:
#      io.rancher.container.pull_image: always
#    tty: true
#    image: alpine:latest
#    stdin_open: true
