version: '2'
# ------ NETWORKS ------------------------
networks:
  monitoring:
    driver: bridge

# ------ CONTAINER -----------------------
services:

  elasticsearch:
    build: elasticsearch/
    image: elasticsearch:latest
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - monitoring
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    stdin_open: true

  logstash:
    build: logstash/
    image: logstash:latest
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044/tcp"
    #networks:
    #  - monitoring
    links:
      - elasticsearch:elasticsearch
    labels:
      io.rancher.container.hostname_override: container_name
    command:
      - -f
      - /etc/logstash/conf.d/
    stdin_open: true

  kibana:
    build: kibana/
    image: kibana:latest
    ports:
      - "5601:5601/tcp"
    networks:
      - monitoring
    links:
      - elasticsearch:elasticsearch
    labels:
      io.rancher.container.hostname_override: container_name
    stdin_open: true

  packetbeat:
    build: packetbeat/
    image: packetbeat:latest
    network_mode: host
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.dns: 'true'
    stdin_open: true

#  dockbeat:
#    image: ingensi/dockbeat:latest
#    environment:
#      PERIOD: 5
#    networks:
#      - monitoring
#    links:
#      - elasticsearch
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock