version: '2'
services:
#  prometheus-rancher-exporter:
  #build: prometheus-rancher-exporter/
#    labels:
#      io.rancher.container.pull_image: always
#    tty: true
#    image: alpine:latest
#    stdin_open: true
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    environment:
      GF_SERVER_ROOT_URL: http://grafana.lab:3000
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,digiapulssi-breadcrumb-panel,jdbranham-diagram-panel,savantly-heatmap-panel,mtanda-heatmap-epoch-panel,mtanda-histogram-panel
    labels:
      io.rancher.sidekicks: grafana-config
    links:
      - influxdb
    volumes_from:
      - grafana-config

  grafana-config:
    build: grafana-config/
    image: grafana-config:latest
    command:
      - cat
    links:
      - influxdb
      - elasticsearch
      - prometheus
    volumes:
      - /var/lib/grafana/

  influxdb:
    image: tutum/influxdb:latest
#    ports:
#      - 2003:2003/tcp
#      - 8083:8083/tcp
#      - 8086:8086/tcp
#      - 8090:8090/tcp
    environment:
      GRAPHITE_BINDING: :2003
      GRAPHITE_DB: rancher
      PRE_CREATE_DB: grafana;prometheus;rancher

  kibana:
    build: kibana/
    image: kibana:latest
    ports:
      - 5601:5601/tcp
    links:
      - elasticsearch
      - influxdb
      - prometheus
    volumes:
      - ./kibana/config/:/opt/kibana/config/

#  alertmanager:
  #build: alertmanager/
#    tty: true
#    image: alpine:latest
#    links:
#    - prometheus:prometheus
#    stdin_open: true

  logstash:
    build: logstash/
    image: logstash:latest
    ports:
      - 5000:5000/tcp
    command:
      - -f
      - /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    links:
      - elasticsearch
      #- influxdb
    stdin_open: true
    tty: true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090/tcp
    labels:
      io.rancher.sidekicks: prometheus-config
    command:
      - -alertmanager.url=http://alertmanager:9093
      - -config.file=/etc/prometheus-config/prometheus.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
    links:
      #- node-exporter
      #- cAdvisor
      - logstash
      #- prometheus-rancher-exporter
    volumes_from:
      - prometheus-config

  prometheus-config:
    build: prometheus-config/
    image: prometheus-config:latest
    #links:
    #  - node-exporter
    volumes:
      - /etc/prometheus-config/

  logspout:
    build: logspout/
    image: logspout:latest
    tty: true
    stdin_open: true
    domainname: lab
    environment:
      EXCLUDE_LABEL: logspout.exclude
      ROUTE_URIS: 'tcp://logstash:5000'
    links:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
      logspout.exclude: 'true'

#  pushgateway:
  #build: pushgateway/
#    tty: true
#    image: alpine:latest
#    links:
#    - prometheus:prometheus
#    stdin_open: true

#  cAdvisor:
  #build: cAdvisor/
#    labels:
#      io.rancher.container.pull_image: always
#    tty: true
#    image: alpine:latest
#    stdin_open: true

  elasticsearch:
    build: elasticsearch/
    image: elasticsearch:latest
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    volumes:
    - ./elasticsearch/config:/etc/elasticsearch

#  node-exporter:
#    build: node-exporter/
#    labels:
#      io.rancher.container.pull_image: always
#    tty: true
#    image: alpine:latest
#    stdin_open: true
