version: '2'
services:
#  graf-db:
#    scale: 0
#  prometheus-rancher-exporter:
#    scale: 0
#  grafana:
#    scale: 0
#  influxdb:
#    scale: 0
#  kibana:
#    scale: 0
#  alertmanager:
#    scale: 0
  logstash:
    scale: 1
#  prometheus:
#    scale: 0
  logspout:
    scale: 1
#  pushgateway:
#    scale: 0
#  cAdvisor:
#    scale: 0
#  elasticsearch:
#    scale: 0
#  node-exporter:
#    scale: 0
